image: node:20.11.0

stages:
  - installation
  - changeset

installation:
  stage: installation
  cache:
    key: $CI_COMMIT_REF_NAME
    policy: push
    paths:
      - node_modules
  script:
    - npm ci

changeset:
  stage: changeset
  cache:
    key: $CI_COMMIT_REF_NAME
    policy: pull
    paths:
      - node_modules
  script:
    - npx changeset status --since=origin/dev
